title:             Maker Society   
email:             makersociety.svq@gmail.com
description:       La comunidad maker de Sevilla
author:            Start Bootstrap
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  makersocietysvq
github_username:   maker-society-svq
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
