title:             Maker Society
email:             makersociety.svq@gmail.com
description:       La comunidad maker de Sevilla
author:            Sevilla Maker Society
baseurl:           ""
url:               "https://maker-society-svq.github.io"

# Social Profiles
twitter_username:  makersocietysvq
github_username:   maker-society-svq
facebook_username: groups/2058902251011477/

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
